application: bean-evaluation
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
  secure: always
  login: required
